// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZo44ho0WCdkHi3ZDA3aZ399oIzVkzDzk',
    appId: '1:989507021943:web:1c13a9a019851cad73ea72',
    messagingSenderId: '989507021943',
    projectId: 'finansa-1b6e8',
    authDomain: 'finansa-1b6e8.firebaseapp.com',
    databaseURL: 'https://finansa-1b6e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finansa-1b6e8.firebasestorage.app',
    measurementId: 'G-NJPG7PNJ7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArpJS9Ohf41YmrpB7VuT6RUEZ9R58nec4',
    appId: '1:989507021943:android:e73e1b8cd0bf0e7d73ea72',
    messagingSenderId: '989507021943',
    projectId: 'finansa-1b6e8',
    databaseURL: 'https://finansa-1b6e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finansa-1b6e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxxkoVgbcQMTANv_36gIwZVF53hhLlacs',
    appId: '1:989507021943:ios:486f9063b86a493973ea72',
    messagingSenderId: '989507021943',
    projectId: 'finansa-1b6e8',
    databaseURL: 'https://finansa-1b6e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finansa-1b6e8.firebasestorage.app',
    iosBundleId: 'com.example.finansaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxxkoVgbcQMTANv_36gIwZVF53hhLlacs',
    appId: '1:989507021943:ios:486f9063b86a493973ea72',
    messagingSenderId: '989507021943',
    projectId: 'finansa-1b6e8',
    databaseURL: 'https://finansa-1b6e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finansa-1b6e8.firebasestorage.app',
    iosBundleId: 'com.example.finansaNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZo44ho0WCdkHi3ZDA3aZ399oIzVkzDzk',
    appId: '1:989507021943:web:c429a8cba18ee6e773ea72',
    messagingSenderId: '989507021943',
    projectId: 'finansa-1b6e8',
    authDomain: 'finansa-1b6e8.firebaseapp.com',
    databaseURL: 'https://finansa-1b6e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finansa-1b6e8.firebasestorage.app',
    measurementId: 'G-XC44X55G8J',
  );

}